### ISSUE TITLE
Empty run time error, no assertion

### ISSUE THREAD

**Issue by danderson00** [browserstack/automate-node-samples#13]
I have followed the instructions in the readme and have a couple of issues when running tests. I'm just running the single test, and can see the test successfully running and completing in the BrowserStack portal, but get a runtime error after the suite runs:

```
Error
    at new RuntimeError (/Users/dale/Projects/webdriverio-browserstack/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (/Users/dale/Projects/webdriverio-browserstack/node_modules/webdriverio/build/lib/utils/RequestHandler.js:313:39)
    at Request.self.callback (/Users/dale/Projects/webdriverio-browserstack/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/dale/Projects/webdriverio-browserstack/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/dale/Projects/webdriverio-browserstack/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
```

Additionally, in a subsequent run, I tried to make the test fail by putting an incorrect title in the assertion, but this had no impact on the test result, the BrowserStack portal still shows the test as passing.

I don't know if this is a webdriverio or BrowserStack issue, but there is very little documentation outside the "happy path" and have no idea how to start resolving this issue.

Any assistance would be greatly appreciated!

**Comment by danderson00** [comment]
For info, I am running MacOS High Sierra 10.13 and Node.js 8.9.1.

**Comment by hrmoller** [comment]
Try lock your webdriverio version to 4.8.0

**Comment by mjawa** [comment]
Thanks for reporting the issue. This issue is fixed now.

**Comment by parris** [comment]
I'm definitely still getting this error still, though it is spurious (1 out of 5 or 6 runs).

Versions:
webdriver - 4.10.1
wdio-browserstack-service - 0.1.14
wdio-mocha-framework - 0.5.12
browserstack-local - 1.3.0

The tests pass successfully, but then this issue will cause the test runner to fail.
